/* Generated by the protocol buffer compiler.  DO NOT EDIT! */
/* Generated from: soa_proxy_msg.proto */

#ifndef PROTOBUF_C_soa_5fproxy_5fmsg_2eproto__INCLUDED
#define PROTOBUF_C_soa_5fproxy_5fmsg_2eproto__INCLUDED

#include <protobuf-c/protobuf-c.h>

PROTOBUF_C__BEGIN_DECLS

#if PROTOBUF_C_VERSION_NUMBER < 1000000
# error This file was generated by a newer version of protoc-c which is incompatible with your libprotobuf-c headers. Please update your headers.
#elif 1001001 < PROTOBUF_C_MIN_COMPILER_VERSION
# error This file was generated by an older version of protoc-c which is incompatible with your libprotobuf-c headers. Please regenerate this file with a newer version of protoc-c.
#endif


typedef struct _SoaProxyRequest SoaProxyRequest;
typedef struct _SoaProxyResponse SoaProxyResponse;


/* --- enums --- */


/* --- messages --- */

struct  _SoaProxyRequest
{
  ProtobufCMessage base;
  char *group_name;
  char *service_name;
  char *service_version;
  ProtobufCBinaryData request;
};
#define SOA_PROXY_REQUEST__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&soa_proxy_request__descriptor) \
    , NULL, NULL, NULL, {0,NULL} }


struct  _SoaProxyResponse
{
  ProtobufCMessage base;
  int32_t status;
  ProtobufCBinaryData response;
};
#define SOA_PROXY_RESPONSE__INIT \
 { PROTOBUF_C_MESSAGE_INIT (&soa_proxy_response__descriptor) \
    , 0, {0,NULL} }


/* SoaProxyRequest methods */
void   soa_proxy_request__init
                     (SoaProxyRequest         *message);
size_t soa_proxy_request__get_packed_size
                     (const SoaProxyRequest   *message);
size_t soa_proxy_request__pack
                     (const SoaProxyRequest   *message,
                      uint8_t             *out);
size_t soa_proxy_request__pack_to_buffer
                     (const SoaProxyRequest   *message,
                      ProtobufCBuffer     *buffer);
SoaProxyRequest *
       soa_proxy_request__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   soa_proxy_request__free_unpacked
                     (SoaProxyRequest *message,
                      ProtobufCAllocator *allocator);
/* SoaProxyResponse methods */
void   soa_proxy_response__init
                     (SoaProxyResponse         *message);
size_t soa_proxy_response__get_packed_size
                     (const SoaProxyResponse   *message);
size_t soa_proxy_response__pack
                     (const SoaProxyResponse   *message,
                      uint8_t             *out);
size_t soa_proxy_response__pack_to_buffer
                     (const SoaProxyResponse   *message,
                      ProtobufCBuffer     *buffer);
SoaProxyResponse *
       soa_proxy_response__unpack
                     (ProtobufCAllocator  *allocator,
                      size_t               len,
                      const uint8_t       *data);
void   soa_proxy_response__free_unpacked
                     (SoaProxyResponse *message,
                      ProtobufCAllocator *allocator);
/* --- per-message closures --- */

typedef void (*SoaProxyRequest_Closure)
                 (const SoaProxyRequest *message,
                  void *closure_data);
typedef void (*SoaProxyResponse_Closure)
                 (const SoaProxyResponse *message,
                  void *closure_data);

/* --- services --- */


/* --- descriptors --- */

extern const ProtobufCMessageDescriptor soa_proxy_request__descriptor;
extern const ProtobufCMessageDescriptor soa_proxy_response__descriptor;

PROTOBUF_C__END_DECLS


#endif  /* PROTOBUF_C_soa_5fproxy_5fmsg_2eproto__INCLUDED */
